name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "front/package-lock.json"
      - run: npm ci
      - run: npm run lint
      - run: npm run test:prod
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage/bobapp
      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Test with Maven
        working-directory: ./back
        run: mvn -B clean verify
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/
      - name: SonarQube Scan (Backend)
        working-directory: ./back
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gdaume24_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD -Dsonar.inclusions=**/back/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    environment: docker_env
    needs: [frontend-tests, backend-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta (frontend)
        id: meta_front
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/projet_10_frontend

      - name: Docker meta (backend)
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/projet_10_backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ${{ steps.meta_front.outputs.tags }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ${{ steps.meta_back.outputs.tags }}
